str="  hello python world 123  " #string methods
print(str.strip(" "))
print(str.upper())
print(str.lower())
print(str.swapcase())
print(str.capitalize())
print(str[0])
print(str[-1])
print(str[2:8])
print(str[-5])
print(str.replace("python", "java"))
print(str.split(" "));print(len(str.split(" "))); #print(count(str.split(" ")))
print(str.count("o"))
print(str.find("python")); print(str.index("python"))
print(str.startswith("hello"))
print(str.endswith("123"))
print(str.isalpha())
print(str.isalnum())
print(str.istitle());print(str.title())
print(str.isprintable())
print(str.center(50))
print(len(str))
